version: "3.8"
volumes:
  postgres-data:
services:
  postgres:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "127.0.0.1:5434:5432"
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "127.0.0.1:3000:3000"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - APP_DB_CONNECTION=postgres://postgres:postgres@postgres:5432/postgres
      - APP_HOSTNAME=http://localhost:3000
    depends_on:
      - postgres